In [18]:
import pandas as pd
import numpy as np

In [19]:
obj1 = pd.read_pickle("targets.pkl")

In [20]:
targets = pd.read_pickle("targets.pkl")
means = targets[0]
sds = targets[1]

df = pd.DataFrame({
    "mean": pd.Series(means),
    "sd": pd.Series(sds)
})

df.index.name = "key"
df = df.reset_index()
df["accuracy"] = np.abs(df["mean"]) / df["sd"]

df

   key      mean        sd      accuracy
0    2  0.999980  0.000198   5059.998255
1    3  1.000174  0.000161   6196.320803
2    5  0.999964  0.000125   8000.691204
3   10  0.999992  0.000088  11314.630038
4   30  0.999930  0.000051  19595.961256
5   50  0.999978  0.000040  25303.316562
6  100  0.999997  0.000028  35783.772754
7  300  1.000007  0.000016  61967.577542
8  500  1.000004  0.000013  79979.740352

In [32]:
import glob
import pandas as pd

combined_df = pd.concat(
    [pd.read_pickle(f) for f in sorted(glob.glob("pickles/*.pkl"))],
    ignore_index=True
)

In [33]:
import os
os.getcwd()

'/insomnia001/home/ar4445/Cheap_Bootstrap_Journal/Simple_Mean_EXP'

In [34]:
combined_df['k'].value_counts()

k
10     288
50     288
100    288
5      288
300    288
500    288
Name: count, dtype: int64

In [35]:
combined_df['D_mult'].value_counts()

D_mult
0.01    288
0.02    288
0.10    288
0.75    288
1.00    288
1.10    288
Name: count, dtype: int64

In [36]:
combined_df.to_pickle("combined_mean_EXP.pkl")

In [9]:
k = 10
stat = "U"
d_mult = 0.01
B = 1


df_filtered = combined_df[
    (combined_df["k"] == k) &
    (combined_df["stat"] == stat) &
    (combined_df["B"] == B)
]

df_filtered.head()

      k stat   n   d  D_mult  B  coverage  average length  n_jobs  simul_size
432  10    U  10   1    0.01  1   0.92500        5.916584       6         800
433  10    U  10   1    0.02  1   0.92500        5.916584       6         800
434  10    U  10   1    0.10  1   0.92500        5.916584       6         800
435  10    U  10   8    0.75  1   0.92625        5.796397       6         800
436  10    U  10  10    1.00  1   0.93625        5.806631       6         800

In [7]:
np.random.SeedSequence(1).spawn(5)

[SeedSequence(
     entropy=1,
     spawn_key=(0,),
 ),
 SeedSequence(
     entropy=1,
     spawn_key=(1,),
 ),
 SeedSequence(
     entropy=1,
     spawn_key=(2,),
 ),
 SeedSequence(
     entropy=1,
     spawn_key=(3,),
 ),
 SeedSequence(
     entropy=1,
     spawn_key=(4,),
 )]

In [8]:
pd.read_pickle("pickles/simulation_36_k500_B5_V_normal_dist_sample_mean.pkl")

FileNotFoundError: [Errno 2] No such file or directory: 'pickles/simulation_36_k500_B5_V_normal_dist_sample_mean.pkl'

In [ ]:
k_seeds = np.random.SeedSequence(1).spawn(5)

In [ ]:
k_seeds

[SeedSequence(
     entropy=1,
     spawn_key=(0,),
 ),
 SeedSequence(
     entropy=1,
     spawn_key=(1,),
 ),
 SeedSequence(
     entropy=1,
     spawn_key=(2,),
 ),
 SeedSequence(
     entropy=1,
     spawn_key=(3,),
 ),
 SeedSequence(
     entropy=1,
     spawn_key=(4,),
 )]

In [ ]:
k_s = [int(s.generate_state(1)[0]) for s in k_seeds]

k_s

[1641411168, 1454127163, 2749604155, 3056722145, 3734005922]